name: Build Docker Image

on:
  push:
    branches: [main, master]
  pull_request:
    types: [opened, ready_for_review, synchronize]
    branches: [main, master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t atlantis-drift-detection .

      - name: Verify image was created
        run: docker images atlantis-drift-detection
